In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv(r'F:\Tutorials\Python\Udemy - Machine Learning Practical 6 Real-World Applications\twitter sentiment\train_E6oV3lV.csv')

In [3]:
dataset.head(5)

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [4]:
import re
import nltk

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [6]:
corpus=[]
for i in range(0,31962):
    review=dataset['tweet'][i]
    review=re.sub('@[\w]*',' ',review)
    review=re.sub('[^a-zA-z#]',' ',review)
    review=review.lower()
    review=review.split()
    review=[word for word in review if len(word)>3]
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(corpus,dataset['label'], test_size = 0.2, random_state = 0)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000)
x_train_vector = cv.fit_transform(x_train).toarray()


In [9]:
print(x_train_vector)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=500,min_samples_leaf=250)
classifier.fit(x_train_vector,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=250, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000)
x_test_vector = cv.fit_transform(x_test).toarray()

In [12]:
y_pred=classifier.predict(x_test_vector)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9361801970905678


In [14]:
test=pd.read_csv(r'F:\Tutorials\Python\Udemy - Machine Learning Practical 6 Real-World Applications\twitter sentiment\test_tweets_anuFYb8.csv')

In [15]:
corpus_test=[]
for i in range(0,17197):
    review=test['tweet'][i]
    review=re.sub('@[\w]*',' ',review)
    review=re.sub('[^a-zA-z#]',' ',review)
    review=review.lower()
    review=review.split()
    review=[word for word in review if len(word)>3]
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus_test.append(review)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000)
corpus_test_vector = cv.fit_transform(corpus_test).toarray()


In [17]:
predictions=classifier.predict(corpus_test_vector)

In [18]:
print(predictions)

[0 0 0 ... 0 0 0]


In [19]:
result=pd.DataFrame({'id':test['id'],'label':predictions})

In [20]:
print(result)

          id  label
0      31963      0
1      31964      0
2      31965      0
3      31966      0
4      31967      0
5      31968      0
6      31969      0
7      31970      0
8      31971      0
9      31972      0
10     31973      0
11     31974      0
12     31975      0
13     31976      0
14     31977      0
15     31978      0
16     31979      0
17     31980      0
18     31981      0
19     31982      0
20     31983      0
21     31984      0
22     31985      0
23     31986      0
24     31987      0
25     31988      0
26     31989      0
27     31990      0
28     31991      0
29     31992      0
...      ...    ...
17167  49130      0
17168  49131      0
17169  49132      0
17170  49133      0
17171  49134      0
17172  49135      0
17173  49136      0
17174  49137      0
17175  49138      0
17176  49139      0
17177  49140      0
17178  49141      0
17179  49142      0
17180  49143      0
17181  49144      0
17182  49145      0
17183  49146      0
17184  49147      0


In [21]:
result.to_csv('test_predictions.csv',index=False)